import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdadb",
        "on-primary-fixed": "#221b00",
        "surface-container-lowest": "#060e20",
        "on-error": "#690005",
        "tertiary-container": "#ffced0",
        "secondary-fixed-dim": "#4edea3",
        "inverse-on-surface": "#283044",
        "surface-container-high": "#222a3d",
        "on-surface-variant": "#d0c6ab",
        "on-secondary-fixed-variant": "#005236",
        "on-background": "#dae2fd",
        "outline": "#999077",
        "inverse-primary": "#705d00",
        "error-container": "#93000a",
        "surface-dim": "#0b1326",
        "tertiary": "#fff4f3",
        "on-primary-fixed-variant": "#544600",
        "surface-tint": "#e9c400",
        "secondary-fixed": "#6ffbbe",
        "on-primary": "#3a3000",
        "primary-fixed-dim": "#e9c400",
        "on-secondary-fixed": "#002113",
        secondary: "#4edea3",
        surface: "#0b1326",
        primary: "#fff6df",
        "on-tertiary-fixed": "#40000d",
        "on-tertiary": "#67001b",
        "on-tertiary-fixed-variant": "#92002a",
        "on-primary-container": "#705e00",
        "on-surface": "#dae2fd",
        background: "#0b1326",
        "on-secondary": "#003824",
        "outline-variant": "#4d4732",
        "inverse-surface": "#dae2fd",
        "surface-variant": "#2d3449",
        "secondary-container": "#00a572",
        error: "#ffb4ab",
        "tertiary-fixed-dim": "#ffb2b7",
        "surface-container-low": "#131b2e",
        "on-error-container": "#ffdad6",
        "primary-container": "#ffd700",
        "surface-bright": "#31394d",
        "primary-fixed": "#ffe16d",
        "on-tertiary-container": "#bd0c3b",
        "on-secondary-container": "#00311f",
        "surface-container-highest": "#2d3449",
        "surface-container": "#171f33",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
export default config;
